### ISSUE TITLE
Make Compatible with RF for 1.16.1

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Maciej916/Industrial-Reborn#8]
## What should be added or changed?
Make your machines compatible with RF

## Why should this be done?
So machines from other mods can use your generators and your machines use other mods' generators.

**Comment by Maciej916** [comment]
There is no plans to make my cables and machines compatible with any other mods. I want to have control over how much energy my machines generates and use. There is too many other mods that produce too much RF and that would make my machines overpowered. I might add something like energy converter that will convert other mods energy to mine in the future.

**Comment by ClaudiusMinimus** [comment]
Thank you

**Comment by papaworld** [comment]
Hi Maciej916, thank you for bring back IC. Been playing with IC2 since 1.7.10. Router Reborn for 1.7.10 had an RF to EU converter which helped out a lot integrating IC2 with RF equipment. And, RedNet had a cable for converting EU to RF. Both came in very handy in our builds. I didn't think of it as overpowered... more like a very nice convenience. ThanX again, well done!
